### ISSUE TITLE
Monorepo using Lerna?

### ISSUE THREAD

**Issue by wwahammy** [bootstrap-styled/bootstrap-styled#117]
## Issue Type

- [ ] Bug (https://github.com/bootstrap-styled/bootstrap-styled/blob/master/.github/CONTRIBUTING.md#bug-reports)
- [x] Feature (https://github.com/bootstrap-styled/bootstrap-styled/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

Right now, it's really hard to fork and modify bootstrap-styled because of all the packages. As an example, [@bootstrap-styled/provider](https://github.com/bootstrap-styled/provider) uses [bootstrap-styled](https://github.com/bootstrap-styled/bootstrap-styled/), [@bootstrap-styled/css-utils](https://github.com/bootstrap-styled/css-utils), and [@bootstrap-styled/css-mixins](https://github.com/bootstrap-styled/css-mixins). Not only does it make it hard to customize but it also makes submit improvements because they happen in a number of different repositories.

Using Lerna would allow bootstrap-styled to move all of the relevant packages into a single repo. Users could then take the entire set of packages at once, modify them and use them for their own needs or submit the changes back.

**Comment by kopax** [comment]
> Right now, it's really hard to fork and modify bootstrap-styled because of all the packages.

It's as usual, could you be more specific on what is "hard"?

> As an example, @bootstrap-styled/provider uses bootstrap-styled, @bootstrap-styled/css-utils, and @bootstrap-styled/css-mixins. 

It's common to have cascades of modules. If you are using ES6, then you probably know a little about the build system dependencies. 

> Not only does it make it hard to customize but it also makes submit improvements because they happen in a number of different repositories.

All the repository are opensource and use github, this is fairly common. We use semantic-release for all ou repo so we just need to merge to master to be able to release a new version. `npm` package manager know how to deal with semver and use the latest good version. If you make a new feature, you should release a `feat(title): description`, if you release a breaking change you should commit a `perf(title): description`, and a fix for an existing feature `fix(title): description`.  I will never accept a commit message that does not respect semver and will break other's code so it's pretty safe. Just do all the modification you need and if you respect this then each release will work properly.

> Using Lerna would allow bootstrap-styled to move all of the relevant packages into a single repo. Users could then take the entire set of packages at once, modify them and use them for their own needs or submit the changes back.

We want bootstrap-styled to be a network of users sharing UI, it does not need to be all stored in one repo. People can make and share what they want and take what they need to build it. If you are writing about the core, then the core is as an example: 

`bootstrap-styled > @bootstrap-styled/v4 +@bootstrap-styled/css-mixins @bootstrap-styled/css-utils @bootstrap-styled/utils`
                
If you write an app:

- if you are not importing css-mixins, css-utils etc... then v4 will still install them. if you import them then it is normal to have it in your `package.json`

If you write a module:

- same rule apply.

There's nothing much complicated, now how do you do in development to test all those features ?

It's pretty simple, just run `npm install ../path-to-project` and it will use your local copy, in each project run `npm run build:lib:watch`, change will be applied in real time.


About lerna, we tought about using monorepo but we are still waiting for https://github.com/semantic-release/semantic-release/issues/193 because we did not found this blocking nor hard and it was not priorized. It will become much easier to use mono repo in the future and we wiwll not have to change our build process.

Thanks for using bootstrap styled and if you are willing to contribute, then I can chat with you on freenode and give you the best tips in real time so you can get started. I am every day around

**Comment by kopax** [comment]
I am closing this since no reply, if you feel this is unresolved or should get additional attention, feel free to reply.
