### ISSUE TITLE
Customize Dropdown

### ISSUE THREAD

**Issue by davidroman0O** [bootstrap-styled/bootstrap-styled#86]
## Issue Type

- [x] Clearly didn't understand how to do it

## Description

I'm playing with `boostrap-styled` but I tried to use the `theme` props on the dropdown component `<Dropdown theme={{}}/>` and adding some style like in the documentation : 

```jsx
<Dropdown
    theme={{
         "$component-active-bg": "#fff",
    }}
>
```

But it doesn't works... Moreover, the caret disapear! 

I tried to look inside of the `defaultProps` and I found a `theme` props, soooo I tired a dirty approach : 

```jsx
<Dropdown
  theme={Object.assign({}, Dropdown.defaultProps.theme, {
      "$component-active-bg": "#fff",
      // "$btn-padding-x": "2rem"
  })}
>
```

But nothing works. 

The documentation says that I need a `shape` type on the `theme` prop with the full list of parameters we can manipulate.

I clearly doing something wrong. I hope someone could show me how I can customize a Dropdown without customizing them all! (Like having two dropdown on the same page without having styling conflict)

## Steps to reproduce

```jsx
<Dropdown
    theme={{
         "$component-active-bg": "#fff",
    }}
>
```

# Versions

- Node/NPM: 8.10
- OS: OSX
- bootstrap-styled: ^3.0.6

Thx a lot ! 😄 

Update : 
It works well on `Button` right now, but not on `Dropdown`...

**Comment by kopax** [comment]
The problem is that if you want to give just 1 theme variable, then the whole default `props.theme` will be overridden by your value.

Currently, we are not merging the two as it may cause additional troubleshoot for the different use case.

If you want to generate a full bootstrap theme just by editing a few variables, I suggest you to use a [`<BootstrapProvider />`](https://github.com/bootstrap-styled/provider).

This one use `makeTheme` function and will calculate a full default bootstrap styled theme.

Another way around is to use the makeTheme when configuring your dropdown:

```jsx
import { makeTheme } from 'bootstrap-styled/lib/theme';

<Dropdown
    theme={makeTheme({
         "$component-active-bg": "#fff",
    })}
/>
```

**Comment by davidroman0O** [comment]
@kopax   I'll try your solution right now!
I'm using it! It's a Next.js app, the `BoostrapProvider` is called on the `_app.js` 😄 

Everything should be setup correctly, I was having some difficulties for the `Dropdown` customization.

Thx for answering, I really appreciate it!

**Comment by davidroman0O** [comment]
Oooook !

In fact, I wanted to customize the button, your code is perfect for the popup!

Using the same thing for the `DropdownToggle` allow me customize it.

It's closed, thanks you a lot for helping me understanding this aspect of `boostrap-styled` 😄
